name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Iniciar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # --- PASSO NOVO ADICIONADO ---
      # Instala o navegador Microsoft Edge nos ambientes que não o possuem.
      - name: Install Microsoft Edge
        # Este passo só executa em Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gpg
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
          sudo rm microsoft.gpg
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable
      - name: Install Microsoft Edge (macOS)
        # Este passo só executa em macOS
        if: runner.os == 'macOS'
        run: brew install --cask microsoft-edge
        
      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Rodar Testes (Linux e macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: PYTHONPATH=. python -m pytest
        
      - name: Rodar Testes (Windows)
        if: runner.os == 'Windows'
        run: |
          $env:PYTHONPATH="."
          python -m pytest